

WHOLE_NOTE = "𝅝 "
HALF_NOTE = "𝅗𝅥 "
QUATER_NOTE = "𝅘𝅥 "
EIGTH_NOTE = "𝅘𝅥𝅮 "
SIXTEENTH_NOTE = "𝅘𝅥𝅯 "
THRITYSEC_NOTE = "𝅘𝅥𝅰 "
SIXTYFORTH_NOTE = "𝅘𝅥𝅱 "
FLAT_SIGN = "♭ "

WHOLE_REST = "𝄻 "
HALF_REST = "𝄼 "
QUATER_REST = "𝄽 "
EIGHTH_REST = "𝄾 "
SIXTEENTH_REST = "𝄿 "
THRITYSEC_REST = "𝅀 "
SIXTYFORTH_REST = "𝅁 "

DOT = u"\u00B7"

NOTE_HEAD = "𝅘 "
NATURAL_SIGN = "♮ "
SHARP_SIGN = "♯ "
FLAT_SIGN = u"\u266D"

BARLINE1 = "𝄀 "
BARLINE2 = "𝄁 "
END_REPEAT = "𝄂 "
START_REPEAT = "𝄃 "

TREBLE_CLEFF = "𝄞 "
DRUM_CLEFF = "𝄥 "
BASS_CLEFF = "𝄢 "
TENOR_CLEFF= "𝄡 "


GHOST_NOTEHEAD = "𝅃 "

BLACK_NOTEHEAD = u"\U0001D158"
VOID_NOTEHEAD = u"\U0001D157"

TRIPLET = "(3) " + QUATER_NOTE
QUINTUPLET = "(5) " + QUATER_NOTE
DOTTED = "."+QUATER_NOTE
DOUBLE_DOTTED = ".."+QUATER_NOTE
