NOTE_HEAD = "𝅘 "
WHOLE_NOTE = "𝅝 "
HALF_NOTE = "𝅗𝅥 "
QUATER_NOTE = "𝅘𝅥 "
EIGHT_NOTE = "𝅘𝅥𝅮 "
SIXTEENTH_NOTE = "𝅘𝅥𝅯 "
THRITYSEC_NOTE = "𝅘𝅥𝅰 "
SIXTYFORTH_NOTE = "𝅘𝅥𝅱 "
FLAT_SIGN = "♭ "
NATURAL_SIGN = "♮ "
SHARP_SIGN = "♯ "

BARLINE1 = "𝄀 "
BARLINE2 = "𝄁 "
END_REPEAT = "𝄂 "
START_REPEAT = "𝄃 "


TREBLE_CLEFF = "𝄞 "
DRUM_CLEFF = "𝄥 "
BASS_CLEFF = "𝄢 "

WHOLE_REST = "𝄻 "
HALF_REST = "𝄼 "
QUATER_REST = "𝄽 "
EIGHTH_REST = "𝄾 "
SIXTEENTH_REST = "𝄿 "
THRITYSEC_REST = "𝅀 "
SIXTYFORTH_REST = "𝅁 "

GHOST_NOTEHEAD = "𝅃 "

BLACK_NOTEHEAD = u"\U0001D158"
VOID_NOTEHEAD = u"\U0001D157"
