[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "guitar-composer"
dynamic = ["version"]
readme = "README.md"
license = ""
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: C",
    "Programming Language :: Python :: 3",
]

[tool.hatch.version]
path = "cmodules/__init__.py"

[tool.hatch.build.targets.wheel.shared-data]
"data/midi_drum_groups.json" = "data/midi_drum_groups.json"
"data/version.txt" = "data/version.txt"
"data/presets" = "data/presets"
"data/effect_config" = "data/effect_config"
"data/instruments" = "data/instruments"
"data/music_theory" = "data/music_theory"
"data/sf_info" = "data/sf_info"
"data/sf" = "data/sf"
"data/assets" = "data/assets"
"data/models" = "data/models"

[tool.hatch.build.targets.sdist]
include = [
    "/src",
]

