from models.note import Note
from typing import List, Optional


class TrackEvent:
    def __init__(self):
        # at what beat in the beat does this event take place?
        self.beat = None


class NoteEvent(TrackEvent, Note):
    def __init__(self):
        TrackEvent.__init__(self)
        Note.__init__(self)

        # hand effects
        self.bend = 0          # pitch bend in half steps
        self.bend_duration = 0  # bend duration in beats
        self.bend_pattern = []  # percentage movement over bend duration time

        # mute percentage
        #   controls the weighting of the guitar muted track.
        self.mute = 0

        # harmonic track percentage
        self.harmonic = 0


class StaffEvent(TrackEvent):
    def __init__(self):
        TrackEvent.__init__(self)
        self.bpm = 120
        self.signature = "4/4"
        self.key = "C"


class ChordEvent(TrackEvent):
    UPSTROKE = 0
    DOWNSTROKE = 1
    NOSTROKE = -1

    def __init__(self):
        super().__init__()
        self.stroke = self.DOWNSTROKE
        self.stroke_duration = 0  # in beats
        self.note_events = []


class EffectPresetEvent(TrackEvent):
    def __init__(self):
        super().__init__()


class AudioClipEvent(TrackEvent):
    def __init__(self):
        super().__init__()

        # play start and end
        self.start_pos = 0
        self.end_pos = 0
        self.loop = False
        self.filename = ""


class TrackEventSequence:
    """ 
    Events are generated by the UI, they result in this sequence being generated.

    This sequence is saved and used to generate a score.
    """

    def __init__(self):
        self.sequence = {}
        self.index = []

    def add(self, beat: int, evt):
        evtList = self.sequence.get(beat, [])
        self.index.append(beat)
        evtList.append(evt)
        self.sequence[beat] = evtList
        self.index.sort()

    def get(self, beat: int) -> Optional[List[TrackEvent]]:
        return self.sequence.get(beat)

    def remove(self, beat: int, evt=None):
        if evt:
            evtList = self.sequence.get(beat)
            if evtList and evt in evtList:
                i = evtList.index(evt)
                del evtList[i]
        elif beat in self.sequence:
            del self.sequence[beat]


class TabCursor:
    BEND_PERIODS = 13

    def __init__(self):
        self.beat = 0
        self.string = 5  # current string being edited
        self.fret = None  # current fret value
        self.duration = 0.25
        self.pitch_bend_histogram = [0] * self.BEND_PERIODS


class Track:
    def __init__(self):
        self.uuid = None
        self.instrument_name = "Acoustic Guitar"
        self.tuning = [
            "E4",
            "B3",
            "G3",
            "D3",
            "A2",
            "E2"
        ]
        # beats from start of track -> [events]
        self.sequence = TrackEventSequence()

        self.tab_cursor = TabCursor()

    def getTabCursor(self) -> TabCursor:
        return self.tab_cursor

    def getSequence(self) -> TrackEventSequence:
        return self.sequence
